### ISSUE TITLE
build under Windows with mingw as compiler

### ISSUE THREAD

**Issue by BLumia** [Wunkolo/libsai#11]
Hi and I'm trying to use this repo to make Qt application can support reading `.sai` files to `QImage` by implementing a Qt imageformats plugin. When using it, I got some issues, and @chirs241097 helped me to resolve some of these issues, and I also would like to send these patches to you :)

https://github.com/Wunkolo/libsai/blob/607ec7acb817b52a4d2bc2682fcd07c0a78b4f19/source/sai.cpp#L230-L236

As can see here, you are using `_WIN32` macro to use [`ifstream::open(const wchar_t*)`](https://docs.microsoft.com/en-us/cpp/standard-library/basic-ifstream-class?view=vs-2019#open) which is a Microsoft STL only function. so maybe checking compiler (`_MSC_VER`) is a better approach for this need.

**Comment by Wunkolo** [comment]
Thanks for the input! I'll merge the PR in too
