### ISSUE TITLE
sai::Tag may need treat data as little-endian

### ISSUE THREAD

**Issue by BLumia** [Wunkolo/libsai#12]
Hi and I'm trying to use this repo to make Qt application can support reading .sai files to QImage by implementing a Qt imageformats plugin. When using it, I got some issues, and @chirs241097 helped me to resolve some of these issues, and I also would like to send these patches to you :)

---------

I'm building and using this lib with mingw 7.3.0 64 bit gcc toolchain under Windows x64. When testing, I found out `sai::Document::GetThumbnail()` always returns null PixelData with width and height as 0. with some debugging I found `Header.Magic != sai::Tag("BM32")` condition is true and cause it return here.

https://github.com/Wunkolo/libsai/blob/607ec7acb817b52a4d2bc2682fcd07c0a78b4f19/source/sai.cpp#L837-L840

Then found that `sai::Tag()` will treat it as big-endian instead of little-endian.

https://github.com/Wunkolo/libsai/blob/607ec7acb817b52a4d2bc2682fcd07c0a78b4f19/include/sai.hpp#L36-L45

I tested locally and returning something like `*reinterpret_cast<const uint32_t*>(TagString);` should works as expected. not sure if it's a clean fix or if we still need to do some endian checking...

Under `enum class BlendingModes` I saw there are also some other use of `sai::Tag`, I'm not sure if this fix can cause other issue, so just leave it here and hope that helps. Let me know if you need any additional information which can help you resolve this issue.

**Comment by BLumia** [comment]
For fixing the `GetThumbnail()` always return invalid data issue, just change the return as below should works.

```
    return
          (TagString[3] << 24)
        | (TagString[2] << 16)
        | (TagString[1] << 8)
        | (TagString[0] << 0);
```

But since `sai::Tag` is still using a lot elsewhere so I'm not sure if fixing it by changing the `sai::Tag` to make it treat data as little-endian is a good idea. If all other place are using it as big endian, maybe we need add a `sai::TagLE()` or something?

**Comment by Wunkolo** [comment]
Oh that's certainly strange, it works fine in its current state on my linux and windows machine though I have not done testing in mingw and such.
"Tag" is intentionally a little utility-function that will create a 32-bit four-byte-identifier that resolves at compile-time into simple assembly(and allows it to be used within enums). Its intent was to easily allow four-character string literals to be turned into a `std::uint32_t` integer type and _should_ behave determinant due to the order of the bytes in the string.

Maybe my template `Tag` function can have a bool/enum in its arguments for explicitly configuring the endian-ness?

Something like:
```cpp
 template<std::size_t N, bool LittleEndian = true> 
 inline constexpr std::uint32_t Tag(const char (&TagString)[N]) 
{
 	if constexpr(LittleEndian)
 	{
 	 	// Little endian result
 	}
 	else
 	{
 	 	// Big endian result
 	}
}
```

**Comment by Wunkolo** [comment]
How's something like this, while keeping it C++11(constexpr-if is C++17)

https://godbolt.org/z/vhpdPa

```cpp
#include <cstddef>
#include <cstdint>

enum class Endian
{
    Little  = 0,
    Big     = 1
};

template<std::size_t N> 
 inline constexpr std::uint32_t Tag(const char (&TagString)[N], Endian Endianness = Endian::Little) 
 { 
 	static_assert(N == 5, "Tag must be 4 characters"); 
    if (Endianness == Endian::Little)
    {
        return 
 		  (TagString[3] << 24) 
 		| (TagString[2] << 16) 
 		| (TagString[1] <<  8) 
 		| (TagString[0] <<  0); 
    }
    else
    {
        return 
 		  (TagString[3] <<  0) 
 		| (TagString[2] <<  8) 
 		| (TagString[1] << 16) 
 		| (TagString[0] << 24); 
    }
 } 


std::uint32_t test[] = {
    Tag("AAAB", Endian::Big),
    Tag("AAAB", Endian::Little),
    Tag("   A", Endian::Big),
    Tag("   A", Endian::Little),
    Tag("A   ", Endian::Big),
    Tag("A   ", Endian::Little),
};
```

**Comment by Wunkolo** [comment]
I was able to re-create the issue and implemented the endian-configured `Tag` with little-endian being the default and it should work now.
0a06e7d629043a9396864182dcf9f9d9d0642a26

I also added a new "Thumbnail" sample for extracting the thumbnail image from a `.sai` file into a `.png` file
https://github.com/Wunkolo/libsai/blob/master/samples/Thumbnail.cpp

**Comment by BLumia** [comment]
Just tested and it works fine after your fix! I'll close this issue for now <3

Will also test on my archlinux later :)
