### ISSUE TITLE
CLI for converting .SAI files to .PSD

### ISSUE THREAD

**Issue by tvaz** [Wunkolo/libsai#15]
Hello, I am looking for a simple way to convert .SAI files to PSD en masse via a command line interface, and I stumbled across this repo. Does this functionality exist in the code, or would an implementation via Bash or Python script for example, be straightfoward? Any advice is appreciated. Thanks :)

**Comment by Wunkolo** [comment]
This code is a library that simply reads from `.sai` files for other programmers to incorporate into their C++ codebase. It doesn't provide any bindings for bash or python as it is a C++ library unfortunately and it does not quite fully support every little caveat of what a .sai file can contain such as the vector-stroke layers that Sai supports.
