### ISSUE TITLE
Document.cpp is unlicensed

### ISSUE THREAD

**Issue by therahedwig** [Wunkolo/libsai#7]
Dumbest thing, but could you stick a license into Document.cpp? KDE's git repository sents me alarm emails when there's no license detected (because downstream Linux distros can block a whole program from being packaged if the licenses make no sense)

**Comment by Wunkolo** [comment]
[Sure no problem](https://github.com/Wunkolo/libsai/commit/462569f943db1ce02f927ecb25fd5431cbc928ab)
It's all just MIT 👌
