### ISSUE TITLE
The Blending Mode Enum won't work when the tag is 3 letters long.

### ISSUE THREAD

**Issue by therahedwig** [Wunkolo/libsai#8]
Here, there's 3 letter tags. If I read data into a layerheader struct, and then convert the blendingmode to a sai::BlendingModes, the entries that are marked here with 0 will not compare right. That is, I have a blending mode that corresponds with multiply, I convert it to the enum, and then compare to sai::BlendingModes::Multiply, and it does not evaluate as true.
```
enum class BlendingModes : std::uint32_t
{
	PassThrough = Tag("pass"),
	Normal      = Tag("norm"),
	Multiply    = Tag("mul\0"),
	Screen      = Tag("scrn"),
	Overlay     = Tag("over"),
	Luminosity  = Tag("add\0"),
	Shade       = Tag("sub\0"),
	LumiShade   = Tag("adsb"),
	Binary      = Tag("cbi\0")
};
```

I was locally able to fix this by just removing the '\0', but I figured I'd make an issue to see if this is the appropriate solution to this.

**Comment by Wunkolo** [comment]
[Did some tests](https://godbolt.org/z/ntLuqA) and found out it's an endian issue of sorts.
The `\0` should be at the beginning.

Added a commit that fixes this.
https://github.com/Wunkolo/libsai/commit/4a104db1b609ee03d8e2891e023b52c21994175d

**Comment by therahedwig** [comment]
Unfortunately, this doesn't seem to work, the only time I get proper results is if I make the last character a space, so 'mul ', 'add ', 'sub '. Debugging `reinterpret_cast<quint8*>(&mode)[0]` on the blendingmode uint32 sai gives, the result is 32, so it's ascii white space?

As an aside seems it's 'cbin', not 'cbi' :)

**Comment by Wunkolo** [comment]
So the actual interpreted values you're finding have the three-letter identifiers use a space(`\x20`) rather than a `\0`? Probably me mis-interpreting the IDA Pro output as I never had to dive into the blending mode stuff myself.
So `Tag("mul\x20") == Tag("mul ") == 'mul '` in this case.
I'll make another commit of these enum fixes

**Comment by Wunkolo** [comment]
https://github.com/Wunkolo/libsai/commit/139eca01affd7a9ebaa5e9f37350d5f60ff5456c

**Comment by therahedwig** [comment]
Works :3 

![image](https://user-images.githubusercontent.com/1759191/64643371-8526f980-d410-11e9-8a00-2641ae4c8862.png)
